kind: Service
apiVersion: v1
metadata:
  name: agent-service
  namespace: cybericebox
spec:
  ports:
    - port: 5454
      protocol: TCP
      targetPort: 5454
  selector:
    app: agent
---
kind: Service
apiVersion: v1
metadata:
  name: agent-service-out
  namespace: cybericebox
spec:
  type: NodePort
  ports:
    - port: 5454
      protocol: TCP
      nodePort: 31554
      targetPort: 5454
  selector:
    app: agent